name: "MagicMirror² (master) and EXT-Detector build Testing"

on: [pull_request]

jobs:
  build:
    name: Test install EXT-Detector
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Checkout MagicMirror²
        uses: actions/checkout@v4
        with:
          repository: MagicMirrorOrg/MagicMirror

      - name: Install MagicMirror²
        run: npm install

      - name: Checkout EXT-Detector
        uses: actions/checkout@v4
        with:
          path: MagicMirror/modules/EXT-Detector

      - name: Install EXT-Detector
        run: npm install
        working-directory: MagicMirror/modules/EXT-Detector
        continue-on-error: false
