name: "MagicMirror² (develop) and EXT-Detector build Testing"

on: [pull_request]

jobs:
  build:
    name: Test install EXT-Detector
    runs-on: ubuntu-latest
    steps:
      - name: "Use Node.js v20.x (latest)"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          check-latest: true

      - name: Checkout MagicMirror² (develop)
        uses: actions/checkout@v4
        with:
          repository: MagicMirrorOrg/MagicMirror
          ref: develop

      - name: Install MagicMirror²
        run: npm install

      - name: Checkout EXT-Detector
        uses: actions/checkout@v4
        with:
          path: MagicMirror/modules/EXT-Detector

      - name: Install EXT-Detector
        run: npm install
        working-directory: MagicMirror/modules/EXT-Detector
        continue-on-error: false
